//#-hidden-code
//
//  See LICENSE folder for this template’s licensing information.
//
//  Abstract:
//  The Swift file containing the source code edited by the user of this playground book.
//


import PlaygroundSupport
import SpriteKit
import UIKit
import BookCore
import PlaygroundSupport



let sceneView = SKView(frame: CGRect(x: 0, y: 0, width: 512, height: 768))
if let scene = GameScene(fileNamed: "GameScene") {
    scene.scaleMode = .aspectFill
    sceneView.presentScene(scene)
    
}



PlaygroundPage.current.liveView = sceneView
PlaygroundPage.current.needsIndefiniteExecution = true


//#-end-hidden-code

/*:
 # A little bit about me

 
 ## Hello, my name is Eletrika!

 I'm on a mission on Earth to improve the way that humans use energy! On my home planet, we are moved by eletricity, just like Earth. So I was always very curious about how humans use it :)

 Isn't it amazing? Energy is the fuel for everything you do! It keeps cities, industries and even their homes up and running

 But since when I arrived, I noticed a huge problem: energy travels a long way to reach human houses, but it is not being used to its fullest. In addition, non-renewable sources such as oil and coal are **still** the most used in the world. This is a big issue, since they are extremely polluting and hurt the nature. Also, they run the risk of being depleted, as they are unable to supply all the world's demand - which grows on a daily basis
  
 Happily, in your planet, there are many tools that you can use to transform energy generated by nature into electrical energy. There are also some small decisions you can make that impact a lot the usage of this resource

 So, I have decided to help humans improve their energy efficiency on Earth before I return to my planet!

 - Important:
For a better experience, view this playground on Split View

 */

 
